##
# Publish new action tag(s) for downstream consumption
##
name: Publish

# Manual or automatic release
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # step 1. 获取源码
      - name: Chekcout 🛎️             # 步骤名
        uses: actions/checkout@master # 使用插件名 => https://github.com/actions/checkout

      # step 2. 安装指定 node
      - name: Use Node  📦              # 步骤名
        uses: actions/setup-node@master # 使用插件名 => https://github.com/actions/setup-node
        with: # 插件携带参数
          node-version: '18' # 指定 node 版本

      # Compile dist/index.js and bundle with action.yml
      # Force push major and minor tags, e.g. v1, v1.0
      # See documentation: https://github.com/JasonEtco/build-and-tag-action
      - uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
