name: Keep the versions up-to-date

on:
  release:
    types: [published, edited]

jobs:
  actions-tagger:
    runs-on: windows-latest
    steps:
      # see: https://github.com/Actions-R-Us/actions-tagger
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
